# Generated by Django 5.2.3 on 2025-06-18 02:01

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='M')),
                ('email', models.TextField(unique=True)),
                ('phone_number', models.TextField(max_length=10)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
    ]
